GET http://localhost:8080/orders
Accept: application/json

###
GET http://localhost:8080/orders/2
Accept: application/json

###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "status" : "created",
  "numProducts" : 5,
  "amount": 84.25
}

###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "status" : "created",
  "numProducts" : 10,
  "amount": 345.52
}

###
PUT http://localhost:8080/orders/2
Content-Type: application/json

{
"status" : "approved",
"numProducts" : 10,
"amount": 345.52
}

###
PUT http://localhost:8080/orders/2
Content-Type: application/json

{
  "status" : "shipped",
  "numProducts" : 10,
  "amount": 345.52
}

###
GET http://localhost:8083/connector-plugins
Content-Type: application/json

###
GET http://localhost:8083/connectors
Content-Type: application/json


###
PUT http://localhost:8083/connectors/filestreamsink-01/config
Content-Type: application/json

{
  "connector.class": "org.apache.kafka.connect.file.FileStreamSinkConnector",
  "value.converter":"org.apache.kafka.connect.storage.StringConverter",
  "tasks.max": 1,
  "file": "/connect/test.sink.txt",
  "topics": "orders"
}